[tool.poetry]
name = "pythonproject8"
version = "0.1.0"
description = ""
authors = ["Egor Shternov <nazivinya@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
